"""CN-1: the foreign harness reproduces every golden vector.

Written from Annex B alone (Python; no reference code), this is the
cross-implementation contract being PROVEN: fixtures generated by the
Rust reference must re-derive byte-identically here.
"""

from __future__ import annotations

import os
from pathlib import Path

import pytest

from unidpp.harness import vectors

REPO = Path(__file__).resolve().parent.parent
CORE = Path(os.environ.get("UNIDPP_CORE", REPO.parent / "unidpp-core"))
FIXTURES = {
    "grid": CORE / "crates" / "grid" / "fixtures" / "canonical",
    "s13": CORE / "crates" / "s13" / "fixtures" / "canonical",
    "signatif": REPO / "tests" / "harness" / "canonical",
}


def _fixture(group: str, name: str) -> dict:
    path = FIXTURES[group] / name
    if not path.exists():
        pytest.skip(f"fixture {path} not present (set UNIDPP_CORE)")
    return vectors.load_fixture(path)


def test_segment_commitment_vector():
    fixture = _fixture("grid", "segment-commitment.json")
    assert vectors.commit_state(bytes.fromhex(fixture["state_hex"])).hex() == fixture["commitment_hex"]


def test_policy_vector():
    fixture = _fixture("grid", "policy.json")
    assert vectors.policy_canonical(fixture["policy"]).hex() == fixture["canonical_hex"]
    import hashlib

    assert hashlib.sha256(fixture["canonical_hex"].encode()).hexdigest() == "" or True
    # digest = sha256(canonical bytes)
    import hashlib as H

    assert H.sha256(bytes.fromhex(fixture["canonical_hex"])).hexdigest() == fixture["digest_hex"]


def test_spine_vector():
    fixture = _fixture("grid", "spine.json")
    assert vectors.spine_root(fixture["commitments"]).hex() == fixture["root_hex"]
    version = int(fixture.get("version", fixture.get("spine", {}).get("version", 1)))
    assert vectors.spine_digest(version, fixture["commitments"]).hex() == fixture["digest_hex"]


def test_spine_proof_vector():
    fixture = _fixture("grid", "spine-proof.json")
    assert vectors.proof_verifies(fixture["proof"], bytes.fromhex(fixture["root_hex"]))


def test_s13_request_vector():
    fixture = _fixture("s13", "request.json")
    assert vectors.request_canonical(fixture["request"]).hex() == fixture["canonical_hex"]


def test_s13_response_vector():
    fixture = _fixture("s13", "response.json")
    assert vectors.response_canonical(fixture["response"]).hex() == fixture["canonical_hex"]


def test_coverage_report_vector():
    fixture = _fixture("s13", "coverage-report.json")
    import hashlib

    canonical = vectors.report_canonical(fixture["report"])
    assert canonical.hex() == fixture["canonical_hex"]
    assert hashlib.sha256(canonical).hexdigest() == fixture["digest_hex"]


def test_attestation_statement_vector():
    fixture = _fixture("signatif", "attestation-statement.json")
    assert vectors.statement_canonical(fixture["statement"]).hex() == fixture["canonical_hex"]


def test_battery_lens_is_deterministic():
    inputs = [
        {"name": "static", "bytes": list(b"cell_model=H-2231,capacity_Ah=52,chemistry=LFP")}
    ]
    assert vectors.battery_lens(inputs) == b"battery-view: cell_model=H-2231, conformity=pass"
